### ISSUE TITLE
Integration of annotations

### ISSUE THREAD

**Issue by Andi963** [xihaoli/STAARpipeline#11]
Hello I have a question based on the STAAR code and its underlying publications.

In the code it says:
`#For each noncoding functional category, the conditional STAAR-B p-value is a p-value from an omnibus test
#' that aggregated conditional Burden(1,25) and Burden(1,1),
#' together with conditional p-values of each test weighted by each annotation using Cauchy method.`
--> So this seems to me like calculate e.g. different burden tests by annotation weights, af weights etc. and integrating them afterwards

But based on your publication it seems to me that you integrated the beta-allele frequency weighting directly with the functional variant annotation and the variant score to generate e.g. QBurden.

Which one is correct?

Best
Andi

**Comment by xihaoli** [comment]
Hi @Andi963,

Thanks for checking. I can confirm the STAAR code and its underlying methodology are consistent. Specifically, STAAR considers different MAF-based weights (using beta distribution density), and for each MAF-based weight (e.g. Beta(1,1)), STAAR incorporates one weighting scheme that uses MAF only as well as K different annotation weights on top of MAF (so K + 1 in total), referring to Figure 1d in the [STAAR publication](https://doi.org/10.1038/s41588-020-0676-4) for both unconditional analysis and conditional analysis. This is also reflected in the unconditional/conditional analysis output from the `STAAR` and `STAARpipeline` packages.

Please let me know if there are any questions.

Best,
Xihao

**Comment by Andi963** [comment]
Many thanks for your answer!
So does that mean that e.g. STAAR-B integrates e.g.:
- a maf weighted test
- a maf AND aPC-Epi weighted test
- an aPC-Epi weighted test

Best and many thanks again,
Andi

**Comment by xihaoli** [comment]
Hi @Andi963,

Thanks for your follow-up. For example, STAAR-B integrates e.g.:

- a maf (beta(1,1)) weighted test, which is equivalent to equal weight since beta(1,1) is used
- a maf (beta(1,1)) AND aPC-Epi weighted test, which is equivalent to an aPC-Epi weighted test
...
- a maf (beta(1,1)) AND aPC-Con weighted test, which is equivalent to an aPC-Con weighted test
- a maf (beta(1,25)) weighted test, which puts more weights on rarer variants in the set
- a maf (beta(1,25)) AND aPC-Epi weighted test
...
- a maf (beta(1,25)) AND aPC-Con weighted test

Hope this is clear.

Best,
Xihao
