### ISSUE TITLE
Minimum number of samples?

### ISSUE THREAD

**Issue by lvclark** [xihaoli/STAARpipeline#12]
I have a dataset with ~700 samples, eventually to increase to ~1000 but I'm testing out STAARpipeline on what I have so far.  I know that is very small for a human GWAS study, but I thought the gene centric and/or sliding window analysis, in combination with the weights from annotations used in STAARpipeline, might bolster the power enough to be worthwhile.

I noticed that my results files from the STAARpipeline_Gene_Centric_Coding.R script just contained a list of `NULL` values.  I went back and stepped through the script manually, and got the following message printed for the first gene:

```
# of selected samples: 721
# of selected variants: 103
# of selected samples: 721
# of selected variants: 12
# of selected samples: 721
# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
# of selected samples: 721
# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
# of selected samples: 721
# of selected variants: 3
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  Number of rare variant in the set is less than 2!
# of selected samples: 721
# of selected variants: 9
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  Number of rare variant in the set is less than 2!
# of selected samples: 721
# of selected variants: 0
Error in STAAR(Geno, obj_nullmodel, Anno.Int.PHRED.sub.category, rare_maf_cutoff = rare_maf_cutoff,  : 
  genotype is not a matrix!
# of selected samples: 721
# of selected variants: 3,724,472
```

If I do `str(results)`:

```
List of 5
 $ plof               : NULL
 $ plof_ds            : NULL
 $ missense           : NULL
 $ disruptive_missense: NULL
 $ synonymous         : NULL
```

Is my dataset just too small, or is there some other issue to be fixed? I am running 0.9.6 from the Docker container because I was working on this back in October, but can change to 0.9.7 if you think that would help.

**Comment by xihaoli** [comment]
Hi @lvclark,

Thanks for your interest in STAARpipeline. Regarding your question, it is indeed that your sample size (n = 721) limits the number of variants in the rare variant set. Currently, the [default MAF cutoff](https://github.com/xihaoli/STAARpipeline-Tutorial/blob/main/STAARpipeline_Gene_Centric_Coding.r) (`rare_maf_cutoff`) used to define rare variants is 0.01 (that is, only variants with MAC < 0.01 * 721 * 2 = 14.42 will be included in the analysis). So it is expected that for a specific gene, all of your results are `NULL`.

To address this, there are two possible ways:

(1) Use a larger `rare_maf_cutoff`, for example 0.05, instead of 0.01 to allow for more variants to be included.
(2) Perform a "conventional" gene-based analysis where all variants, regardless of their functional annotations, will be included in the set. In such a case, you only have one variant set per gene. When defining a variant set, you can perform a union of `plof`, `missense`, etc to form one larger set.

Hope this helps.

Best,
Xihao
